### ISSUE TITLE
sidekiq still crashes

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/snpr#458]
I noticed that the sidekiq machine was down again: 

```
Dec 12 21:52:51 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T20:52:32.030Z 147 TID-ifi6s ActionMailer::DeliveryJob JID-51e5ea177ed818d85f1debea INFO: start
Dec 12 22:04:18 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:01:09.968Z 147 TID-ipl9c ERROR: Error connecting to Redis on 10.130.159.2:6379 (Redis::TimeoutError)
Dec 12 22:04:21 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:01:32.641Z 147 TID-iplm4 ERROR: heartbeat: Connection timed out
Dec 12 22:04:24 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:01:57.404Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection'
Dec 12 22:04:57 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:03:26.607Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
Dec 12 22:06:05 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:05:03.171Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
Dec 12 22:07:19 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:06:07.587Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
Dec 12 22:07:33 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:07:19.540Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
Dec 12 22:08:11 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:07:35.452Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
Dec 12 22:08:28 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:08:14.096Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
Dec 12 22:08:41 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:08:30.625Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
Dec 12 22:08:53 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:08:44.475Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
Dec 12 22:09:05 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:08:52.582Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
Dec 12 22:09:17 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:09:06.567Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:1799:in `block in zrangebyscore'
Dec 12 22:09:44 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:09:21.129Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
Dec 12 22:10:16 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:09:47.558Z 147 TID-ipl9c ERROR: /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
Dec 12 22:10:31 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:10:09.274Z 147 TID-ifie0 Preparsing JID-89f937f10e0b75c4505535db INFO: start
Dec 12 22:10:44 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:10:18.953Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
Dec 12 22:11:15 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:10:47.654Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:1798:in `zrangebyscore'
Dec 12 22:11:39 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:11:17.956Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
Dec 12 22:12:13 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:11:40.418Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:15:in `each'
Dec 12 22:12:28 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:12:02.389Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
Dec 12 22:12:47 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:12:31.547Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:95:in `block in redis'
Dec 12 22:13:01 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:12:48.919Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
Dec 12 22:13:16 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:13:02.336Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
Dec 12 22:13:41 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:13:21.104Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
Dec 12 22:13:55 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:13:41.971Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
Dec 12 22:14:09 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:13:57.103Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
Dec 12 22:14:37 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:14:09.671Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:92:in `redis'
Dec 12 22:15:07 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:14:35.793Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
Dec 12 22:15:42 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:15:07.842Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:77:in `enqueue'
Dec 12 22:16:07 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:15:46.765Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/scheduled.rb:68:in `block in start'
Dec 12 22:17:15 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:16:13.614Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:17:in `watchdog'
Dec 12 22:17:16 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:16:39.307Z 147 TID-ipl9c ERROR: /home/app/snpr/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:26:in `block in safe_thread'
Dec 12 22:17:17 sidekiq docker/f5cb22d4164f[567]: Dec 12 21:17:02 opensnp cron[145]: (CRON) error (can't fork)
```

Are the last errors in the log. I had to manually restart via the hetzner console.

**Comment by philippbayer** [comment]
Did Sidekiq crash or did the connection to the Redis server die and then Sidekiq crashed from there?

```
Dec 12 22:04:18 sidekiq docker/f5cb22d4164f[567]: 2017-12-12T21:01:09.968Z 147 TID-ipl9c ERROR: Error connecting to Redis on 10.130.159.2:6379 (Redis::TimeoutError)
```

**Comment by gedankenstuecke** [comment]
Well, I couldn’t even ssh to the whole machine. So no clue? I did flush all dead jobs out of the redis queue now. Maybe they helps

**Comment by philippbayer** [comment]
A blank slate :)
![image](https://user-images.githubusercontent.com/413885/33918118-aebc3d56-dfec-11e7-8cb9-f2ea579f4f02.png)

**Comment by gedankenstuecke** [comment]
Yep, let’s see how it performs now :)

**Comment by tsujigiri** [comment]
Still looks like the sidekiq machine ran out of memory, since CRON wans't able to fork and the machine wasn't reachable.

**Comment by gedankenstuecke** [comment]
Yeah, any suggestions on how to best find out what exactly is eating up that memory?

**Comment by tsujigiri** [comment]
Hm... maybe limit the workers to 1 and see what job is running when it happens? Not sure that's such a good idea, since it will of course clog the pipes...

**Comment by gedankenstuecke** [comment]
Yeah, maybe it’s better to just check the log file more once it happens next time around and see what the last running tasks were?

**Comment by tsujigiri** [comment]
Worth a try.

**Comment by gedankenstuecke** [comment]
For now it seems to work 🤷‍♀️

**Comment by philippbayer** [comment]
I think this works now, good to close?

**Comment by gedankenstuecke** [comment]
Yes :)
